### ISSUE TITLE
Bump dependencies in GitHub Actions with dependabot

### ISSUE THREAD

**Issue by PerchunPak** [py-mine/mcstatus#419]
This can be done by adding this in `.github/dependabot.yml`'s `updates:` list:

```yml
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  labels:
    - "area: dependencies"
```

Because PRs like #416 shouldn't be made by hand.
